### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement 115sha1link (from versions: none) ERROR: No matching distribution found for 115sha1link

### ISSUE THREAD

**Issue by theNorthWindBlow** [Xavier-Lam/115sha1link#1]
ERROR: Could not find a version that satisfies the requirement 115sha1link (from versions: none)
ERROR: No matching distribution found for 115sha1link

**Comment by Xavier-Lam** [comment]
抱歉我没有上传这个包,readme提到的安装方法是错的.
你只需要下载[115sha1link.py](https://github.com/Xavier-Lam/115sha1link/blob/master/115sha1link.py) 并直接使用.

I am really sorry, I didn't upload the pip package, the installment readme mentioned is wrong.
You just need to download [115sha1link.py](https://github.com/Xavier-Lam/115sha1link/blob/master/115sha1link.py) and use it.
